swagger: "2.0"
info:
  description: |
    The deadline_1 chain code shows the first steps in developing a chaincode that
    can read/write strings onto the blockchain and can expose these functions as REST API. THIS SAMPLE
    CODE MAY BE USED SOLELY AS PART OF THE TEST AND EVALUATION OF THE ALMERYS/BE|YS BLOCKCHAIN
    SERVICE (THE "SERVICE") AND IN ACCORDANCE WITH THE AGREEMENT FOR THE SERVICE. THIS SAMPLE CODE
    PROVIDED "AS IS", WITHOUT ANY WARRANTY, ESCROW, TRAINING, MAINTENANCE, OR SERVICE OBLIGATIONS
    WHATSOEVER ON THE PART OF ALMERYS/BE|YS.
  version: "1.0"
  title: "deadline_1"

consumes:
  - application/x-www-form-urlencoded

paths:

  /{id}:

    post:
      operationId: write
      summary: Write a text (once) by ID
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: text
        in: formData
        required: true
        type: string
      responses:
        200:
          description: Text Written
        500:
          description: Failed

    get:
     operationId: read
     summary: Read text by ID
     parameters:
     - name: id
       in: path
       required: true
       type: string
     produces:
     - text/plain
     responses:
       200:
         description: OK
       500:
         description: Failed

